[package]
name = "test-cdrs"
version = "0.1.0"
authors = ["Alex Pikalov <alex.pikalov.khar@gmail.com>"]
edition = "2018"

[dependencies]
cdrs = {version = "2", features = ["v4"]}
cdrs_helpers_derive = "0.1.0"
uuid = {version = "0.7", features = ["v4"]}
time = "0.1"
r2d2 = "0.8.2"
